-- Initial schema (spec 04). Ids are UUIDv7 generated by the app (DAT-01).
-- Timestamps used in comparisons come from the app clock (DAT-22), so no column defaults to now().

CREATE TABLE apps (
  id         uuid PRIMARY KEY,
  name       text NOT NULL CHECK (name <> ''),
  created_at timestamptz NOT NULL
);

CREATE TABLE api_keys (
  id         uuid PRIMARY KEY,
  app_id     uuid NOT NULL REFERENCES apps (id),
  key_hash   bytea NOT NULL UNIQUE, -- SHA-256 of the key; the key itself is never stored (SEC-11)
  prefix     text NOT NULL,
  created_at timestamptz NOT NULL,
  revoked_at timestamptz
);
CREATE INDEX api_keys_by_app ON api_keys (app_id);

CREATE TYPE endpoint_disabled_reason AS ENUM ('manual', 'auto_failing');

CREATE TABLE endpoints (
  id                         uuid PRIMARY KEY,
  app_id                     uuid NOT NULL REFERENCES apps (id),
  customer_id                text NOT NULL,
  url                        text NOT NULL,
  event_types                text[] NOT NULL CHECK (cardinality(event_types) >= 1),
  secret                     text NOT NULL,
  previous_secret            text,
  previous_secret_expires_at timestamptz,
  rate_limit_rps             integer NOT NULL CHECK (rate_limit_rps BETWEEN 1 AND 1000),
  max_concurrency            integer NOT NULL CHECK (max_concurrency BETWEEN 1 AND 100),
  first_failure_at           timestamptz,
  disabled_at                timestamptz,
  disabled_reason            endpoint_disabled_reason,
  created_at                 timestamptz NOT NULL,
  updated_at                 timestamptz NOT NULL,
  deleted_at                 timestamptz, -- soft delete: old deliveries still resolve their endpoint
  CONSTRAINT endpoints_disabled_reason_iff_disabled CHECK ((disabled_at IS NULL) = (disabled_reason IS NULL)),
  CONSTRAINT endpoints_previous_secret_has_expiry CHECK ((previous_secret IS NULL) = (previous_secret_expires_at IS NULL))
);
-- Endpoints of a customer that are not soft-deleted (dispatcher lookup, API list, API-30 count).
CREATE INDEX endpoints_by_customer ON endpoints (app_id, customer_id) WHERE deleted_at IS NULL;

CREATE TABLE events (
  id            uuid PRIMARY KEY,
  app_id        uuid NOT NULL REFERENCES apps (id),
  customer_id   text NOT NULL,
  type          text NOT NULL,
  payload       jsonb NOT NULL,
  created_at    timestamptz NOT NULL,
  dispatched_at timestamptz, -- set by the dispatcher; null = not fanned out yet (R2b)
  requeued_at   timestamptz  -- set by reconciler R2b (RCN-03)
);
CREATE INDEX events_by_customer ON events (app_id, customer_id, created_at DESC, id DESC);
CREATE INDEX events_by_created ON events (created_at);
CREATE INDEX events_undispatched ON events (created_at) WHERE dispatched_at IS NULL;

CREATE TABLE idempotency_keys (
  app_id       uuid NOT NULL REFERENCES apps (id),
  key          text NOT NULL CHECK (char_length(key) BETWEEN 1 AND 255),
  -- Written before its event in the same transaction (ING-03.6), so checked at commit.
  event_id     uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  request_hash bytea NOT NULL,
  created_at   timestamptz NOT NULL,
  PRIMARY KEY (app_id, key)
);
CREATE INDEX idempotency_keys_by_event ON idempotency_keys (event_id);
CREATE INDEX idempotency_keys_by_created ON idempotency_keys (created_at);

-- Holds only events not yet relayed; the relay deletes rows once published (REL-07).
CREATE TABLE outbox (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_id    uuid NOT NULL UNIQUE REFERENCES events (id) ON DELETE CASCADE,
  traceparent text,
  created_at  timestamptz NOT NULL
);

CREATE TYPE delivery_status AS ENUM ('pending', 'in_flight', 'succeeded', 'failed');
CREATE TYPE delivery_failed_reason AS ENUM ('exhausted', 'endpoint_deleted', 'endpoint_disabled');

CREATE TABLE deliveries (
  id                 uuid PRIMARY KEY,
  event_id           uuid NOT NULL REFERENCES events (id),
  endpoint_id        uuid NOT NULL REFERENCES endpoints (id),
  status             delivery_status NOT NULL,
  failed_reason      delivery_failed_reason,
  attempt_count      integer NOT NULL CHECK (attempt_count >= 0),
  next_attempt_at    timestamptz NOT NULL,
  lease_until        timestamptz,
  lease_token        uuid, -- fencing token, new on every claim (WRK-09)
  gate_blocked_count integer NOT NULL CHECK (gate_blocked_count >= 0),
  traceparent        text,
  last_error         text,
  created_at         timestamptz NOT NULL,
  updated_at         timestamptz NOT NULL,
  UNIQUE (event_id, endpoint_id), -- DAT-10: makes fan-out idempotent
  CONSTRAINT deliveries_failed_reason_iff_failed CHECK ((status = 'failed') = (failed_reason IS NOT NULL)),
  CONSTRAINT deliveries_lease_token_iff_in_flight CHECK ((status = 'in_flight') = (lease_token IS NOT NULL)),
  CONSTRAINT deliveries_lease_until_iff_lease_token CHECK ((lease_token IS NULL) = (lease_until IS NULL))
);
CREATE INDEX deliveries_by_endpoint ON deliveries (endpoint_id, status, created_at DESC, id DESC);
CREATE INDEX deliveries_pending_due ON deliveries (next_attempt_at) WHERE status = 'pending';
CREATE INDEX deliveries_in_flight_lease ON deliveries (lease_until) WHERE status = 'in_flight';

CREATE TYPE attempt_error AS ENUM (
  'timeout', 'connection_refused', 'dns', 'tls', 'ssrf_blocked', 'circuit_open'
);

CREATE TABLE attempts (
  id               uuid PRIMARY KEY,
  delivery_id      uuid NOT NULL REFERENCES deliveries (id),
  attempt_number   integer NOT NULL CHECK (attempt_number >= 1),
  started_at       timestamptz NOT NULL,
  duration_ms      integer NOT NULL CHECK (duration_ms >= 0),
  http_status      integer CHECK (http_status BETWEEN 100 AND 599),
  response_snippet text,
  error            attempt_error,
  UNIQUE (delivery_id, attempt_number), -- DAT-11: two workers sending one delivery surfaces here
  CONSTRAINT attempts_http_status_xor_error CHECK ((http_status IS NULL) <> (error IS NULL)) -- either an HTTP response or a transport error
);
